### ISSUE TITLE
Pulling m2 into master

### ISSUE THREAD

**Issue by Phelimb** [iqbal-lab/Mykrobe-predictor#103]
Making an issue instead of a PR as the branches don't share commit history so we won't be able to pull via github. 

@iqbal-lab I think m2 is stable enough now to be merged into master. Below are the comparisons of the AMR prediction results on the full sets from the NCOMMS paper for staph and TB. There are a few minor changes - mostly an increase in specificity in m2 with no loss in sensitivity. 

I've also included a comparison of the walker panel with that from the original panel as this is new in m2 also. 

## TB

Ana1 - f943547e7cfb965bc0c6aa24934778765a9d188a (master)

Drug | Total | FN(R) | FP(S) | VME | ME | sensitivity | specificity | PPV | NPV
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | 2971 | 23 (371) | 23 (2600) | 6.2% (4.2%-9.1%) | 0.9% (0.6%-1.3%) | 93.8% (90.9%-95.8%) | 99.1% (98.7%-99.4%) | 93.8% (90.9%-95.8%) | 99.1% (98.7%-99.4%)
Capreomycin | 326 | 7 (56) | 14 (270) | 12.5% (6.2%-23.6%) | 5.2% (3.1%-8.5%) | 87.5% (76.4%-93.8%) | 94.8% (91.5%-96.9%) | 77.8% (66.1%-86.3%) | 97.3% (94.6%-98.7%)
all | 11881 | 259 (1753) | 176 (10128) | 14.8% (13.2%-16.5%) | 1.7% (1.5%-2.0%) | 85.2% (83.5%-86.8%) | 98.3% (98.0%-98.5%) | 89.5% (87.9%-90.8%) | 97.5% (97.1%-97.8%)
Isoniazid | 3011 | 68 (586) | 23 (2425) | 11.6% (9.3%-14.4%) | 0.9% (0.6%-1.4%) | 88.4% (85.6%-90.7%) | 99.1% (98.6%-99.4%) | 95.7% (93.7%-97.2%) | 97.2% (96.5%-97.8%)
Amikacin | 330 | 5 (62) | 6 (268) | 8.1% (3.5%-17.5%) | 2.2% (1.0%-4.8%) | 91.9% (82.5%-96.5%) | 97.8% (95.2%-99.0%) | 90.5% (80.7%-95.6%) | 98.1% (95.7%-99.2%)
Ethambutol | 2987 | 56 (238) | 94 (2749) | 23.5% (18.6%-29.3%) | 3.4% (2.8%-4.2%) | 76.5% (70.7%-81.4%) | 96.6% (95.8%-97.2%) | 65.9% (60.2%-71.3%) | 97.9% (97.3%-98.4%)
Kanamycin | 106 | 4 (11) | 1 (95) | 36.4% (15.2%-64.6%) | 1.1% (0.2%-5.7%) | 63.6% (35.4%-84.8%) | 98.9% (94.3%-99.8%) | 87.5% (52.9%-97.8%) | 95.9% (90.0%-98.4%)
Streptomycin | 1579 | 90 (394) | 9 (1185) | 22.8% (19.0%-27.2%) | 0.8% (0.4%-1.4%) | 77.2% (72.8%-81.0%) | 99.2% (98.6%-99.6%) | 97.1% (94.6%-98.5%) | 92.9% (91.3%-94.2%)
Quinolones | 571 | 6 (35) | 6 (536) | 17.1% (8.1%-32.7%) | 1.1% (0.5%-2.4%) | 82.9% (67.3%-91.9%) | 98.9% (97.6%-99.5%) | 82.9% (67.3%-91.9%) | 98.9% (97.6%-99.5%)

Ana2 - 0e9e70d295250bb1c7ecfd4a31c1100d17311d21 - m2

Drug | Total | FN(R) | FP(S) | VME | ME | sensitivity | specificity | PPV | NPV
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | 2971 | 19 (371) | 20 (2600) | 5.1% (3.3%-7.9%) | 0.8% (0.5%-1.2%) | 94.9% (92.1%-96.7%) | 99.2% (98.8%-99.5%) | 94.6% (91.8%-96.5%) | 99.3% (98.9%-99.5%)
Capreomycin | 326 | 6 (56) | 12 (270) | 10.7% (5.0%-21.5%) | 4.4% (2.6%-7.6%) | 89.3% (78.5%-95.0%) | 95.6% (92.4%-97.4%) | 80.6% (69.2%-88.6%) | 97.7% (95.1%-99.0%)
all | 11881 | 233 (1753) | 166 (10128) | 13.3% (11.8%-15.0%) | 1.6% (1.4%-1.9%) | 86.7% (85.0%-88.2%) | 98.4% (98.1%-98.6%) | 90.2% (88.6%-91.5%) | 97.7% (97.4%-98.0%)
Isoniazid | 3011 | 65 (586) | 21 (2425) | 11.1% (8.8%-13.9%) | 0.9% (0.6%-1.3%) | 88.9% (86.1%-91.2%) | 99.1% (98.7%-99.4%) | 96.1% (94.2%-97.5%) | 97.4% (96.7%-97.9%)
Amikacin | 330 | 4 (62) | 4 (268) | 6.5% (2.5%-15.4%) | 1.5% (0.6%-3.8%) | 93.5% (84.6%-97.5%) | 98.5% (96.2%-99.4%) | 93.5% (84.6%-97.5%) | 98.5% (96.2%-99.4%)
Ethambutol | 2987 | 55 (238) | 93 (2749) | 23.1% (18.2%-28.9%) | 3.4% (2.8%-4.1%) | 76.9% (71.1%-81.8%) | 96.6% (95.9%-97.2%) | 66.3% (60.5%-71.6%) | 98.0% (97.4%-98.4%)
Kanamycin | 106 | 0 (11) | 0 (95) | 0.0% (0.0%-25.9%) | 0.0% (0.0%-3.9%) | 100.0% (74.1%-100.0%) | 100.0% (96.1%-100.0%) | 100.0% (74.1%-100.0%) | 100.0% (96.1%-100.0%)
Streptomycin | 1579 | 78 (394) | 10 (1185) | 19.8% (16.2%-24.0%) | 0.8% (0.5%-1.5%) | 80.2% (76.0%-83.8%) | 99.2% (98.5%-99.5%) | 96.9% (94.4%-98.3%) | 93.8% (92.3%-95.0%)
Quinolones | 571 | 6 (35) | 6 (536) | 17.1% (8.1%-32.7%) | 1.1% (0.5%-2.4%) | 82.9% (67.3%-91.9%) | 98.9% (97.6%-99.5%) | 82.9% (67.3%-91.9%) | 98.9% (97.6%-99.5%)

diff ana2 - ana1

Drug | Total (+/-)  | TP  (+/-)  | FP  (+/-)  | TN  (+/-)  | FN  (+/-)  | sensitivity (+/-)  | specificity (+/-)
----- |----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | +0.000000 | +4.000000 | -3.000000 | +3.000000 | -4.000000 | +1.100000 | +0.100000
Capreomycin | +0.000000 | +1.000000 | -2.000000 | +2.000000 | -1.000000 | +1.800000 | +0.800000
all | +0.000000 | +26.000000 | -10.000000 | +10.000000 | -26.000000 | +1.500000 | +0.100000
Isoniazid | +0.000000 | +3.000000 | -2.000000 | +2.000000 | -3.000000 | +0.500000 | +0.000000
Amikacin | +0.000000 | +1.000000 | -2.000000 | +2.000000 | -1.000000 | +1.600000 | +0.700000
Ethambutol | +0.000000 | +1.000000 | -1.000000 | +1.000000 | -1.000000 | +0.400000 | +0.000000
Kanamycin | +0.000000 | +4.000000 | -1.000000 | +1.000000 | -4.000000 | +36.400000 | +1.100000
Streptomycin | +0.000000 | +12.000000 | +1.000000 | -1.000000 | -12.000000 | +3.000000 | +0.000000
Quinolones | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000

## Staph

compare master 4c8dc62f435c686d39bdf3ba29bdf980317fda71 vs d3c269b5c4a639d219cee9215835126301c2d6b1 (m2)

	./scripts/compare.py --analysis summary --markdown /data2/users/phelim/ana/staph/mykrobe/pheno/comid_to_combined_truth.json --ana1 /data2/users/phelim/ana/staph/atlas/amr/4c8dc62f435c686d39bdf3ba29bdf980317fda71/C000*.json --ana2 /data2/users/phelim/ana/staph/atlas/amr/d3c269b5c4a639d219cee9215835126301c2d6b1/C000*.json > summary_compare_staph_4c8dc62f43_d3c269b5c4a.txt

Ana1

Drug | Total | FN(R) | FP(S) | VME | ME | sensitivity | specificity | PPV | NPV
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | 1029 | 1 (10) | 1 (1019) | 10.0% (1.8%-40.4%) | 0.1% (0.0%-0.6%) | 90.0% (59.6%-98.2%) | 99.9% (99.4%-100.0%) | 90.0% (59.6%-98.2%) | 99.9% (99.4%-100.0%)
Clindamycin | 1029 | 2 (178) | 9 (851) | 1.1% (0.3%-4.0%) | 1.1% (0.6%-2.0%) | 98.9% (96.0%-99.7%) | 98.9% (98.0%-99.4%) | 95.1% (91.0%-97.4%) | 99.8% (99.1%-99.9%)
all | 12309 | 38 (2042) | 70 (10267) | 1.9% (1.4%-2.5%) | 0.7% (0.5%-0.9%) | 98.1% (97.5%-98.6%) | 99.3% (99.1%-99.5%) | 96.6% (95.8%-97.3%) | 99.6% (99.5%-99.7%)
Vancomycin | 1029 | 0 (2) | 0 (1027) | 0.0% (0.0%-65.7%) | 0.0% (0.0%-0.4%) | 100.0% (34.3%-100.0%) | 100.0% (99.6%-100.0%) | 100.0% (34.3%-100.0%) | 100.0% (99.6%-100.0%)
Methicillin | 1029 | 3 (218) | 5 (811) | 1.4% (0.5%-4.0%) | 0.6% (0.3%-1.4%) | 98.6% (96.0%-99.5%) | 99.4% (98.6%-99.7%) | 97.7% (94.8%-99.0%) | 99.6% (98.9%-99.9%)
Mupirocin | 1029 | 0 (53) | 6 (976) | 0.0% (0.0%-6.8%) | 0.6% (0.3%-1.3%) | 100.0% (93.2%-100.0%) | 99.4% (98.7%-99.7%) | 89.8% (79.5%-95.3%) | 100.0% (99.6%-100.0%)
Trimethoprim | 1029 | 5 (62) | 5 (967) | 8.1% (3.5%-17.5%) | 0.5% (0.2%-1.2%) | 91.9% (82.5%-96.5%) | 99.5% (98.8%-99.8%) | 91.9% (82.5%-96.5%) | 99.5% (98.8%-99.8%)
Ciprofloxacin | 1029 | 14 (244) | 9 (785) | 5.7% (3.4%-9.4%) | 1.1% (0.6%-2.2%) | 94.3% (90.6%-96.6%) | 98.9% (97.8%-99.4%) | 96.2% (93.0%-98.0%) | 98.2% (97.0%-98.9%)
Penicillin | 1029 | 5 (838) | 13 (191) | 0.6% (0.3%-1.4%) | 6.8% (4.0%-11.3%) | 99.4% (98.6%-99.7%) | 93.2% (88.7%-96.0%) | 98.5% (97.4%-99.1%) | 97.3% (93.8%-98.8%)
Tetracycline | 1029 | 0 (48) | 3 (981) | 0.0% (0.0%-7.4%) | 0.3% (0.1%-0.9%) | 100.0% (92.6%-100.0%) | 99.7% (99.1%-99.9%) | 94.1% (84.1%-98.0%) | 100.0% (99.6%-100.0%)
Erythromycin | 1029 | 4 (219) | 3 (810) | 1.8% (0.7%-4.6%) | 0.4% (0.1%-1.1%) | 98.2% (95.4%-99.3%) | 99.6% (98.9%-99.9%) | 98.6% (96.0%-99.5%) | 99.5% (98.7%-99.8%)
FusidicAcid | 2019 | 4 (170) | 16 (1849) | 2.4% (0.9%-5.9%) | 0.9% (0.5%-1.4%) | 97.6% (94.1%-99.1%) | 99.1% (98.6%-99.5%) | 91.2% (86.2%-94.5%) | 99.8% (99.4%-99.9%)

Ana2

Drug | Total | FN(R) | FP(S) | VME | ME | sensitivity | specificity | PPV | NPV
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | 1029 | 1 (10) | 1 (1019) | 10.0% (1.8%-40.4%) | 0.1% (0.0%-0.6%) | 90.0% (59.6%-98.2%) | 99.9% (99.4%-100.0%) | 90.0% (59.6%-98.2%) | 99.9% (99.4%-100.0%)
Clindamycin | 1029 | 2 (178) | 7 (851) | 1.1% (0.3%-4.0%) | 0.8% (0.4%-1.7%) | 98.9% (96.0%-99.7%) | 99.2% (98.3%-99.6%) | 96.2% (92.3%-98.1%) | 99.8% (99.1%-99.9%)
all | 12309 | 38 (2042) | 60 (10267) | 1.9% (1.4%-2.5%) | 0.6% (0.5%-0.8%) | 98.1% (97.5%-98.6%) | 99.4% (99.2%-99.5%) | 97.1% (96.3%-97.7%) | 99.6% (99.5%-99.7%)
Vancomycin | 1029 | 0 (2) | 0 (1027) | 0.0% (0.0%-65.7%) | 0.0% (0.0%-0.4%) | 100.0% (34.3%-100.0%) | 100.0% (99.6%-100.0%) | 100.0% (34.3%-100.0%) | 100.0% (99.6%-100.0%)
Methicillin | 1029 | 3 (218) | 5 (811) | 1.4% (0.5%-4.0%) | 0.6% (0.3%-1.4%) | 98.6% (96.0%-99.5%) | 99.4% (98.6%-99.7%) | 97.7% (94.8%-99.0%) | 99.6% (98.9%-99.9%)
Mupirocin | 1029 | 0 (53) | 4 (976) | 0.0% (0.0%-6.8%) | 0.4% (0.2%-1.0%) | 100.0% (93.2%-100.0%) | 99.6% (99.0%-99.8%) | 93.0% (83.3%-97.2%) | 100.0% (99.6%-100.0%)
Trimethoprim | 1029 | 5 (62) | 4 (967) | 8.1% (3.5%-17.5%) | 0.4% (0.2%-1.1%) | 91.9% (82.5%-96.5%) | 99.6% (98.9%-99.8%) | 93.4% (84.3%-97.4%) | 99.5% (98.8%-99.8%)
Ciprofloxacin | 1029 | 14 (244) | 8 (785) | 5.7% (3.4%-9.4%) | 1.0% (0.5%-2.0%) | 94.3% (90.6%-96.6%) | 99.0% (98.0%-99.5%) | 96.6% (93.5%-98.3%) | 98.2% (97.1%-98.9%)
Penicillin | 1029 | 5 (838) | 12 (191) | 0.6% (0.3%-1.4%) | 6.3% (3.6%-10.7%) | 99.4% (98.6%-99.7%) | 93.7% (89.3%-96.4%) | 98.6% (97.5%-99.2%) | 97.3% (93.8%-98.8%)
Tetracycline | 1029 | 0 (48) | 4 (981) | 0.0% (0.0%-7.4%) | 0.4% (0.2%-1.0%) | 100.0% (92.6%-100.0%) | 99.6% (99.0%-99.8%) | 92.3% (81.8%-97.0%) | 100.0% (99.6%-100.0%)
Erythromycin | 1029 | 4 (219) | 3 (810) | 1.8% (0.7%-4.6%) | 0.4% (0.1%-1.1%) | 98.2% (95.4%-99.3%) | 99.6% (98.9%-99.9%) | 98.6% (96.0%-99.5%) | 99.5% (98.7%-99.8%)
FusidicAcid | 2019 | 4 (170) | 12 (1849) | 2.4% (0.9%-5.9%) | 0.6% (0.4%-1.1%) | 97.6% (94.1%-99.1%) | 99.4% (98.9%-99.6%) | 93.3% (88.6%-96.1%) | 99.8% (99.4%-99.9%)

diff ana2 - ana1

Drug | Total (+/-)  | TP  (+/-)  | FP  (+/-)  | TN  (+/-)  | FN  (+/-)  | sensitivity (+/-)  | specificity (+/-)
----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000
Clindamycin | +0.000000 | +0.000000 | -2.000000 | +2.000000 | +0.000000 | +0.000000 | +0.300000
all | +0.000000 | +0.000000 | -10.000000 | +10.000000 | +0.000000 | +0.000000 | +0.100000
Vancomycin | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000
Methicillin | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000
Mupirocin | +0.000000 | +0.000000 | -2.000000 | +2.000000 | +0.000000 | +0.000000 | +0.200000
Trimethoprim | +0.000000 | +0.000000 | -1.000000 | +1.000000 | +0.000000 | +0.000000 | +0.100000
Ciprofloxacin | +0.000000 | +0.000000 | -1.000000 | +1.000000 | +0.000000 | +0.000000 | +0.100000
Penicillin | +0.000000 | +0.000000 | -1.000000 | +1.000000 | +0.000000 | +0.000000 | +0.500000
Tetracycline | +0.000000 | +0.000000 | +1.000000 | -1.000000 | +0.000000 | +0.000000 | -0.100000
Erythromycin | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000
FusidicAcid | +0.000000 | +0.000000 | -4.000000 | +4.000000 | +0.000000 | +0.000000 | +0.300000

	./scripts/compare.py --analysis diff --markdown /data2/users/phelim/ana/staph/mykrobe/pheno/comid_to_combined_truth.json --ana1 /data2/users/phelim/ana/staph/atlas/amr/4c8dc62f435c686d39bdf3ba29bdf980317fda71/C000*.json --ana2 /data2/users/phelim/ana/staph/atlas/amr/d3c269b5c4a639d219cee9215835126301c2d6b1/C000*.json > diff_compare_staph_4c8dc62f43_d3c269b5c4a.txt

sample | drug | truth | ana1 | ana2
---|---|---|---|---|
C00001446 | Ciprofloxacin | S | R | S
C00012813 | Ciprofloxacin | S | S | R
C00003248 | Ciprofloxacin | S | S | R
C00002655 | Ciprofloxacin | S | R | S
C00001249 | Ciprofloxacin | S | S | R
C00003397 | Ciprofloxacin | S | S | R
C00001215 | Ciprofloxacin | S | R | S
C00007091 | Ciprofloxacin | S | R | S
C00003099 | Penicillin | S | r | S
C00003385 | Tetracycline | S | S | r
C00013239 | Ciprofloxacin | S | R | S
C00013344 | FusidicAcid | S | r | S
C00003226 | FusidicAcid | S | R | S

## Walker-2015 panel (TB) new in M2

compare 8776690f00eb8c404363ae506e765937df4b3fb9 bradley with walker

	./scripts/compare.py --markdown /data2/users/phelim/ana/tb/mykrobe/pheno/comid_to_combined_truth.json  --ana1 /data2/users/phelim/ana/tb/atlas/amr/8776690f00eb8c404363ae506e765937df4b3fb9/bradley-2015/*.json --ana2 /data2/users/phelim/ana/tb/atlas/amr/8776690f00eb8c404363ae506e765937df4b3fb9/walker-2015/*.json  > summary_compare_8776690f0_bradley_walker.txt
	
Ana1 - ncomms catalog

Drug | Total | FN(R) | FP(S) | VME | ME | sensitivity | specificity | PPV | NPV
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | 2971 | 19 (371) | 20 (2600) | 5.1% (3.3%-7.9%) | 0.8% (0.5%-1.2%) | 94.9% (92.1%-96.7%) | 99.2% (98.8%-99.5%) | 94.6% (91.8%-96.5%) | 99.3% (98.9%-99.5%)
Capreomycin | 326 | 6 (56) | 12 (270) | 10.7% (5.0%-21.5%) | 4.4% (2.6%-7.6%) | 89.3% (78.5%-95.0%) | 95.6% (92.4%-97.4%) | 80.6% (69.2%-88.6%) | 97.7% (95.1%-99.0%)
all | 14843 | 411 (1968) | 169 (12875) | 20.9% (19.1%-22.7%) | 1.3% (1.1%-1.5%) | 79.1% (77.3%-80.9%) | 98.7% (98.5%-98.9%) | 90.2% (88.7%-91.5%) | 96.9% (96.6%-97.2%)
Isoniazid | 3013 | 65 (586) | 21 (2427) | 11.1% (8.8%-13.9%) | 0.9% (0.6%-1.3%) | 88.9% (86.1%-91.2%) | 99.1% (98.7%-99.4%) | 96.1% (94.2%-97.5%) | 97.4% (96.7%-97.9%)
Amikacin | 330 | 4 (62) | 4 (268) | 6.5% (2.5%-15.4%) | 1.5% (0.6%-3.8%) | 93.5% (84.6%-97.5%) | 98.5% (96.2%-99.4%) | 93.5% (84.6%-97.5%) | 98.5% (96.2%-99.4%)
Pyrazinamide | 2957 | 177 (214) | 3 (2743) | 82.7% (77.1%-87.2%) | 0.1% (0.0%-0.3%) | 17.3% (12.8%-22.9%) | 99.9% (99.7%-100.0%) | 92.5% (80.1%-97.4%) | 93.9% (93.0%-94.7%)
Ethambutol | 2990 | 56 (239) | 93 (2751) | 23.4% (18.5%-29.2%) | 3.4% (2.8%-4.1%) | 76.6% (70.8%-81.5%) | 96.6% (95.9%-97.2%) | 66.3% (60.5%-71.6%) | 97.9% (97.3%-98.4%)
Kanamycin | 106 | 0 (11) | 0 (95) | 0.0% (0.0%-25.9%) | 0.0% (0.0%-3.9%) | 100.0% (74.1%-100.0%) | 100.0% (96.1%-100.0%) | 100.0% (74.1%-100.0%) | 100.0% (96.1%-100.0%)
Streptomycin | 1579 | 78 (394) | 10 (1185) | 19.8% (16.2%-24.0%) | 0.8% (0.5%-1.5%) | 80.2% (76.0%-83.8%) | 99.2% (98.5%-99.5%) | 96.9% (94.4%-98.3%) | 93.8% (92.3%-95.0%)
Quinolones | 571 | 6 (35) | 6 (536) | 17.1% (8.1%-32.7%) | 1.1% (0.5%-2.4%) | 82.9% (67.3%-91.9%) | 98.9% (97.6%-99.5%) | 82.9% (67.3%-91.9%) | 98.9% (97.6%-99.5%)

Ana2 - walker catalog

Drug | Total | FN(R) | FP(S) | VME | ME | sensitivity | specificity | PPV | NPV
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | 2970 | 12 (371) | 40 (2599) | 3.2% (1.9%-5.6%) | 1.5% (1.1%-2.1%) | 96.8% (94.4%-98.1%) | 98.5% (97.9%-98.9%) | 90.0% (86.6%-92.6%) | 99.5% (99.2%-99.7%)
Capreomycin | 326 | 5 (56) | 15 (270) | 8.9% (3.9%-19.2%) | 5.6% (3.4%-9.0%) | 91.1% (80.8%-96.1%) | 94.4% (91.0%-96.6%) | 77.3% (65.8%-85.7%) | 98.1% (95.6%-99.2%)
all | 14839 | 170 (1968) | 279 (12871) | 8.6% (7.5%-10.0%) | 2.2% (1.9%-2.4%) | 91.4% (90.0%-92.5%) | 97.8% (97.6%-98.1%) | 86.6% (85.0%-88.0%) | 98.7% (98.5%-98.9%)
Isoniazid | 3012 | 41 (586) | 24 (2426) | 7.0% (5.2%-9.4%) | 1.0% (0.7%-1.5%) | 93.0% (90.6%-94.8%) | 99.0% (98.5%-99.3%) | 95.8% (93.8%-97.1%) | 98.3% (97.7%-98.8%)
Amikacin | 330 | 4 (62) | 4 (268) | 6.5% (2.5%-15.4%) | 1.5% (0.6%-3.8%) | 93.5% (84.6%-97.5%) | 98.5% (96.2%-99.4%) | 93.5% (84.6%-97.5%) | 98.5% (96.2%-99.4%)
Pyrazinamide | 2956 | 51 (214) | 50 (2742) | 23.8% (18.6%-30.0%) | 1.8% (1.4%-2.4%) | 76.2% (70.0%-81.4%) | 98.2% (97.6%-98.6%) | 76.5% (70.4%-81.7%) | 98.1% (97.6%-98.6%)
Ethambutol | 2989 | 20 (239) | 121 (2750) | 8.4% (5.5%-12.6%) | 4.4% (3.7%-5.2%) | 91.6% (87.4%-94.5%) | 95.6% (94.8%-96.3%) | 64.4% (59.2%-69.3%) | 99.2% (98.8%-99.5%)
Kanamycin | 106 | 0 (11) | 0 (95) | 0.0% (0.0%-25.9%) | 0.0% (0.0%-3.9%) | 100.0% (74.1%-100.0%) | 100.0% (96.1%-100.0%) | 100.0% (74.1%-100.0%) | 100.0% (96.1%-100.0%)
Streptomycin | 1579 | 33 (394) | 19 (1185) | 8.4% (6.0%-11.5%) | 1.6% (1.0%-2.5%) | 91.6% (88.5%-94.0%) | 98.4% (97.5%-99.0%) | 95.0% (92.3%-96.8%) | 97.2% (96.2%-98.0%)
Quinolones | 571 | 4 (35) | 6 (536) | 11.4% (4.5%-25.9%) | 1.1% (0.5%-2.4%) | 88.6% (74.1%-95.5%) | 98.9% (97.6%-99.5%) | 83.8% (68.9%-92.3%) | 99.3% (98.1%-99.7%)

diff ana2 - ana1

Drug | Total (+/-)  | TP  (+/-)  | FP  (+/-)  | TN  (+/-)  | FN  (+/-)  | sensitivity (+/-)  | specificity (+/-)
----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
Rifampicin | -1.000000 | +7.000000 | +20.000000 | -21.000000 | -7.000000 | +1.900000 | -0.700000
Capreomycin | +0.000000 | +1.000000 | +3.000000 | -3.000000 | -1.000000 | +1.800000 | -1.200000
all | -4.000000 | +241.000000 | +110.000000 | -114.000000 | -241.000000 | +12.300000 | -0.900000
Isoniazid | -1.000000 | +24.000000 | +3.000000 | -4.000000 | -24.000000 | +4.100000 | -0.100000
Amikacin | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000
Pyrazinamide | -1.000000 | +126.000000 | +47.000000 | -48.000000 | -126.000000 | +58.900000 | -1.700000
Ethambutol | -1.000000 | +36.000000 | +28.000000 | -29.000000 | -36.000000 | +15.000000 | -1.000000
Kanamycin | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000 | +0.000000
Streptomycin | +0.000000 | +45.000000 | +9.000000 | -9.000000 | -45.000000 | +11.400000 | -0.800000
Quinolones | +0.000000 | +2.000000 | +0.000000 | +0.000000 | -2.000000 | +5.700000 | +0.000000

**Comment by iqbal-lab** [comment]
Accepted - go ahead and merge
