### ISSUE TITLE
paired-end reads

### ISSUE THREAD

**Issue by afkoeppel** [iqbal-lab/Mykrobe-predictor#106]
I'm working with some TB data that I'd like to analyze with Mykrobe, but my reads are paired-end.
Is there an option in mykrobe for handling paired-end reads as input?  I'm not seeing it in the documentation so I apologize if I just missed it.  
I could align them to a TB reference and use a bam file as input, but since I have several samples from different TB strains I'd prefer to use the original fastq files. 
I've considered just combining the R1s and R2s into one file and just treating them as single-end reads, or concatenating the sequences with a single N between the R1 and R2 reads, but I'm not sure which is preferable.  
Does anyone have a recommendation for the best way to handle this?

**Comment by Phelimb** [comment]
We don't explicitly used the paired end information. You can either concatenate the reads as you describe above or run with two sequence files at runtime. 

e.g.

`mykrobe predict ERR117639 tb -1 /download/ena/ERR117639_R1.gz /download/ena/ERR117639_R2.gz`
