### ISSUE TITLE
Probe generation and paralogs

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/Mykrobe-predictor#110]
Reminder of an issue we discussed previously. Removing kmers from a probe which are known to occur elsewhere might improve the robustness of genotyping. One reason this matters is when we start messing around with changing the kmer; dropping the kmer will increase the chances of part of the probe existing elsewhere.

**Comment by Phelimb** [comment]
Fixed in https://github.com/Mykrobe-tools/mykrobe
