### ISSUE TITLE
Ensuring probes do not extend too far

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/Mykrobe-predictor#111]
Probes for SNPs/indels should not extend beyond the variant - all kmers should overlap the variant. Otherwise, you add coverage to both alleles from shared flanks. Not a massive deal for illumina (although why add pointless noise) but I think would be a bigger issue for nanopore data when we already have enough problems without adding to them.

That said, I'm sure I have seen/mostly see things where one allele has covg 0.
So probes can't be _always_ 63, as Phelim speculated today.

ie maybe there is no issue here

**Comment by Phelimb** [comment]
Fixed in https://github.com/Mykrobe-tools/mykrobe
