### ISSUE TITLE
Remove requirement of seeing 100% of an allele for nanopore data

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/Mykrobe-predictor#115]
For Illumina data it has been reasonable to demand that the full allele (all kmers covering the mutation) be detected in reads. For nanopore data, with such a high error rate, this is not appropriate, and we shoud remove this constraint and allow our models to choose for us.

We see examples where sample is S, and we have a lot of covg on the S allele, but not quite 100%
eg the following, where the models would clearly do the right thing if we were not forcing the issue with this threshold that forcibly sets the log likelihood to -9999999.

                           "coverage": {
                                "alternate": {
                                    "percent_coverage": 100.0, 
                                    "median_depth": 1.0, 
                                    "min_non_zero_depth": 1.0
                                }, 
                                "reference": {
                                    "percent_coverage": 95.24, 
                                    "median_depth": 6.0, 
                                    "min_non_zero_depth": 2.0
                                }
                            }
                        }, 
                        "genotype": [
                            1, 
                            1
                        ], 
                        "variant": null, 
                        "genotype_likelihoods": [
                            -99999999, 
                            -99999999, 
                            -24.96258653163734
                        ],

**Comment by Phelimb** [comment]
fixed in https://github.com/Mykrobe-tools/mykrobe
