### ISSUE TITLE
mykrobe predict: error: argument species:

### ISSUE THREAD

**Issue by hirenbioinfo** [iqbal-lab/Mykrobe-predictor#122]
mykrobe predict ERR117639 ./ERR117639*.gz tb

Error : 
mykrobe predict: error: argument species: invalid choice: 'demo_input_file_for_M.tuberculosis_app.fastq' (choose from 'staph', 'tb')

**Comment by iqbal-lab** [comment]
Your arguments are in the wrong order. Check the Readme.

**Comment by hirenbioinfo** [comment]
Could not make it out. Can you please have a look
$mykrobe predict ERR117639 tb -1 ./ERR117639*.gz  
Last few lines of error message
 WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-C517T
WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-C517G
WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-G1484A
WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-G1484T
WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-G1484C
WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-G515A
WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-G515T
WARNING:mykatlas.typing.typer.genotyper:Fewer ref alleles than alt alleles for alt-G515C
Traceback (most recent call last):
  File "/home/user1/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/home/user1/.local/lib/python2.7/site-packages/mykrobe/mykrobe_predictor.py", line 99, in main
    args.func(parser, args)
  File "/home/user1/.local/lib/python2.7/site-packages/mykrobe/mykrobe_predictor.py", line 32, in run_subtool
    run(parser, args)
  File "/home/user1/.local/lib/python2.7/site-packages/mykrobe/cmds/amr.py", line 180, in run
    sequence_confidence_threshold=args.min_gene_conf                      
TypeError: __init__() got an unexpected keyword argument 'include_hom_alt_calls'

**Comment by Phelimb** [comment]
@hirenbioinfo this should be fixed in https://github.com/Mykrobe-tools/mykrobe
