### ISSUE TITLE
IndexError: list index out of range        exception on Linux but not Mac

### ISSUE THREAD

**Issue by harrismia** [iqbal-lab/Mykrobe-predictor#126]
Hello, 

        I am getting the error message:   IndexError: list index out of range when I try to run mykrobe predict on our linux environment.   When I run it on my Mac Book Pro it works fine.  The error message is below: 

        Any ideas about why this is happening?   Thanks in advance!

mykrobe predict SRR5486866 tb --seq ./SRR5486866_1.fastq.gz
INFO:root:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-walker-probe-set-feb-09-2017.fasta.gz
Traceback (most recent call last):
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv2/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv2/lib/python2.7/site-packages/mykrobe/mykrobe_predictor.py", line 125, in main
    args.func(parser, args)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv2/lib/python2.7/site-packages/mykrobe/mykrobe_predictor.py", line 34, in run_subtool
    run(parser, args)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv2/lib/python2.7/site-packages/mykrobe/cmds/amr.py", line 134, in run
   cp.run()
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv2/lib/python2.7/site-packages/mykatlas/typing/typer/genotyper.py", line 74, in run
    self._parse_covgs()
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv2/lib/python2.7/site-packages/mykatlas/typing/typer/genotyper.py", line 128, in _parse_covgs
    row)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv2/lib/python2.7/site-packages/mykatlas/typing/typer/genotyper.py", line 118, in _parse_summary_covgs_row
    return row[0], int(row[2]), int(row[3]), 100 * float(row[4]), int(row[5])
IndexError: list index out of range

**Comment by iqbal-lab** [comment]
What precise version of predictor are you using - did you get it from github? Do you have a commit number? How did  you install , and has it worked for you before?

**Comment by harrismia** [comment]
Hi,    
 
  We did get if from github.  For the linux version: typing mykrobe --version   gives :   mykrobe v0.5.6-0-gbd7923a-dirty

   The same command on my Mac Book Pro gives:  mykrobe v0.5.1-0-g04fef92     I see that they are different.   I have been using the version on my Mac Book but we have never tried using it on our linux cluster before. 

I didn't do the install on the linux cluster so I will find out the details and respond.   Thanks,   
  Michael

**Comment by Phelimb** [comment]
@harrismia Could you upload the output of `pip freeze` when run within your virtualenv ? This looks like the version of `mykatlas` is incompatible with the version of `mykrobe`.

**Comment by Phelimb** [comment]
It looks like the local install of mccortex seems to fail with anaconda venvs. You might need to reinstall mccortex. 

```
	git clone --recursive https://github.com/iqbal-lab/Mykrobe-predictor.git
	cd Mykrobe-predictor
	cd mccortex
	make    
	export PATH=$(pwd)/bin:$PATH
	cd ..
```

The version should read:
```
mccortex31 --version 
mccortex=v0.0.3-482-g22410ea
```

**Comment by harrismia** [comment]
Dear Mykrobe-predictor support team:

I have recompiled mccortex31 and copied the executable under mykrobe’s bin folder. Sadly, “mykrobe predict” still fails. I wonder if “mykatlas==0.6.1” is an incorrect  version. Will wait for comments from Phelim Bradley (please forward his reply to me). Thanks!

» mccortex31 --version
Error: Unrecognised command: --version
usage: mccortex31 <command> [options] <args>
version: mccortex=v0.0.3-482-g22410ea zlib=1.2.8 htslib=1.2.1-250-gfa6ed9a ASSERTS=ON hash=Lookup3 CHECKS=ON k=3..31

Commands:   breakpoints  use a trusted assembled genome to call large events
            bubbles      find bubbles in graph which are potential variants
            build        construct cortex graph from FASTA/FASTQ/BAM
            calls2vcf    convert bubble/breakpoint calls to VCF
           check        load and check graph (.ctx) and path (.ctp) files
            clean        clean errors from a graph
            contigs      assemble contigs for a sample
            correct      error correct reads
            coverage     print contig coverage
            dist         make colour kmer distance matrix
            index        index a sorted cortex graph file
            inferedges   infer graph edges between kmers before calling `thread`
            join         combine graphs, filter graph intersections
            links        clean and plot link files (.ctp)
            pjoin        merge path files (.ctp)
            popbubbles   pop bubbles in the population graph
            pview        text view of a cortex path file (.ctp)
            reads        filter reads against a graph
            rmsubstr     reduce set of strings to remove substrings
            server       interactively query the graph
            sort         sort the kmers in a graph file
            subgraph     filter a subgraph using seed kmers
            thread       thread reads through cleaned graph to make links
            uniqkmers    generate random unique kmers
            unitigs      pull out unitigs in FASTA, DOT or GFA format
            vcfcov       coverage of a VCF against cortex graphs
            vcfgeno      genotype a VCF after running vcfcov
            view         text view of a cortex graph file (.ctx)

  Type a command with no arguments to see help.

Common Options:
  -h, --help            Help message
  -q, --quiet           Silence status output normally printed to STDERR
  -f, --force           Overwrite output files if they already exist
  -m, --memory <M>      Memory e.g. 1GB [default: 1GB]
  -n, --nkmers <H>      Hash entries [default: 4M, ~4 million]
  -t, --threads <T>     Limit on proccessing threads [default: 2]
  -o, --out <file>      Output file
  -p, --paths <in.ctp>  Links file to load (can specify multiple times)

(mykrobeenv) [appbuild@ai-submit1](master|✔)» module show mykrobe
-------------------------------------------------------------------
/sysapps/cluster/modules/all/mykrobe/0.5.6-Python-3.5:

module-whatis         Description: Mykrobe Predictor analyses the whole genome of a bacterial sample, all within a couple of minutes, and predicts which drugs the infection is resistant to. - Homepage: https://github.com/iqbal-lab/Mykrobe-predictor
conflict           mykrobe
prepend-path           CPATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/include
prepend-path           LD_LIBRARY_PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib
prepend-path           LIBRARY_PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib
prepend-path           MANPATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/share/man
prepend-path           PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin
prepend-path           PKG_CONFIG_PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/pkgconfig
setenv                        EBROOTGEMINI /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv
setenv                        EBVERSIONGEMINI 0.5.6
prepend-path           PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv
-------------------------------------------------------------------

(mykrobeenv) [appbuild@ai-submit1](master|✔)» ls /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin
2to3        easy_install      mykrobe      pydoc3.5           python3-config  vcf_melt
2to3-3.5    easy_install-3.5  openssl      python             pyvenv          vcf_sample_filter.py
activate    f2py              pasteurize   python3            pyvenv-3.5      wheel
atlas       futurize          pip          python3.5          sqlite3         wish8.5
conda       idle3             __pycache__  python3.5-config   tclsh8.5        xz
c_rehash    idle3.5           pydoc        python3.5m         unxz
deactivate  mccortex31        pydoc3       python3.5m-config  vcf_filter.py

(mykrobeenv) [appbuild@ai-submit1](master|✔)» which mccortex31
~/eb_files/Mykrobe-predictor/Mykrobe-predictor/mccortex/bin/mccortex31

(mykrobeenv) [appbuild@ai-submit1](master|✔)» cp ~/eb_files/Mykrobe-predictor/Mykrobe-predictor/mccortex/bin/mccortex31 /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin/.

(mykrobeenv) [appbuild@ai-submit1](master|✔)» mykrobe predict SRR5486866 tb --seq /hpcdata/bcbb/tbportal/genomics/SequencingCenterDownloads/Borstel/Romania_50samples/TBprofiler/SRR5486866_1.fastq.gz
INFO:root:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-walker-probe-set-feb-09-2017.fasta.gz
Traceback (most recent call last):
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykrobe/mykrobe_predictor.py", line 125, in main
    args.func(parser, args)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykrobe/mykrobe_predictor.py", line 34, in run_subtool
    run(parser, args)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykrobe/cmds/amr.py", line 134, in run
    cp.run()
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 74, in run
    self._parse_covgs()
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 128, in _parse_covgs
    row)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 118, in _parse_summary_covgs_row
    return row[0], int(row[2]), int(row[3]), 100 * float(row[4]), int(row[5])
IndexError: list index out of range

Sincerely Yours,

Sergei Y. Ponomarev (NIH/NIAID) [C], PhD,  Contractor
Senior Systems Administrator - Linux and High Performance Computing Team
SRA International, Inc., A CSRA Company
Operations and Engineering Branch
Email: sergei.ponomarev@nih.gov<mailto:sergei.ponomarev@nih.gov>
Work phone: 301-761-6731, Mobile: 301-502-1673
5601 Fishers Lane, 6A66, Rockville, MD 20852
NIAID, National Institutes of Health, DHHS

Disclaimer:
The information in this e-mail and any of its attachments is confidential and may contain sensitive information.  It should not be used by anyone who is not the original intended recipient.  If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices.  National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender’s own and not expressly made on behalf of the NIAID by one of its representatives.

From: "Harris, Michael (NIH/NIAID) [E]" <michael.harris2@nih.gov>
Date: Monday, July 24, 2017 at 9:52 AM
To: "Ponomarev, Sergei (NIH/NIAID) [C]" <sergei.ponomarev@nih.gov>
Cc: NIAID OEB HPC Team <NIAIDOEBHPCTeam@mail.nih.gov>
Subject: Re: [iqbal-lab/Mykrobe-predictor] IndexError: list index out of range exception on Linux but not Mac (#126)

Thanks Sergei!

Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764  |  Mobile 301-509-0233
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.


From: "Ponomarev, Sergei (NIH/NIAID) [C]" <sergei.ponomarev@nih.gov>
Date: Monday, July 24, 2017 at 9:39 AM
To: "Harris, Michael (NIH/NIAID) [E]" <michael.harris2@nih.gov>
Cc: NIAID OEB HPC Team <NIAIDOEBHPCTeam@mail.nih.gov>
Subject: Re: [iqbal-lab/Mykrobe-predictor] IndexError: list index out of range exception on Linux but not Mac (#126)

Thanks, Michael. I will go ahead and recompile mccortex!

Sincerely Yours,

Sergei Y. Ponomarev (NIH/NIAID) [C], PhD,  Contractor
Senior Systems Administrator - Linux and High Performance Computing Team
SRA International, Inc., A CSRA Company
Operations and Engineering Branch
Email: sergei.ponomarev@nih.gov<mailto:sergei.ponomarev@nih.gov>
Work phone: 301-761-6731, Mobile: 301-502-1673
5601 Fishers Lane, 6A66, Rockville, MD 20852
NIAID, National Institutes of Health, DHHS

Disclaimer:
The information in this e-mail and any of its attachments is confidential and may contain sensitive information.  It should not be used by anyone who is not the original intended recipient.  If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices.  National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender’s own and not expressly made on behalf of the NIAID by one of its representatives.

From: "Harris, Michael (NIH/NIAID) [E]" <michael.harris2@nih.gov>
Date: Monday, July 24, 2017 at 9:34 AM
To: "Ponomarev, Sergei (NIH/NIAID) [C]" <sergei.ponomarev@nih.gov>
Subject: FW: [iqbal-lab/Mykrobe-predictor] IndexError: list index out of range exception on Linux but not Mac (#126)

FYI..

Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764  |  Mobile 301-509-0233
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by iqbal-lab** [comment]
I'm just going on holiday, so will ping @Phelimb

**Comment by noporpoise** [comment]
Looks like Mykrobe-predictor should be using the McCortex `vcfgeno` command instead of `geno`.

**Comment by Phelimb** [comment]
So, I have a branch of mccortex where geno is a valid command that should work with Mykrobe predictor. 

https://github.com/phelimb/mccortex/tree/genotype

I'm not 100% sure what's causing this error but it seems to be a version clash between mccortex, or mykaltlas. 

You have the correct mykatlas but the mccortex version should be v0.0.3-481-gbbe4edf-dirty

Which you can get manually by running 

`git clone -b genotype https://github.com/phelimb/mccortex`

**Comment by joshualoving** [comment]
When I compile https://github.com/phelimb/mccortex/tree/genotype, I get the same version number mccortex=v0.0.3-482-g22410ea, not v0.0.3-481-gbbe4edf-dirty
