### ISSUE TITLE
"mccortex geno" invalid command

### ISSUE THREAD

**Issue by RaSieb** [iqbal-lab/Mykrobe-predictor#130]
possibly related to #126 : I installed Mykrobe on linux using pip, and mccortex separately using clone and make. mccortex runs when tested alone, and is in PATH. 
Running mykrobe, however, returns an error where mykrobe tries to run a command "**mccortex31** **geno** [...]" which is not recognised by mccortex. 

Error message: 
mykrobe predict test2 staph --mccortex31_path /srv/data/AS/RASI/Mykrobe/mccortex/bin/mccortex31 -1 55-100-060*.gz
INFO:root:Running AMR prediction with panels data/panels/staph-species-160227.fasta.gz, data/panels/staph-amr-bradley_2015-feb-17-2017.fasta.gz
DEBUG:mykatlas.cortex.mccortex:running /srv/data/AS/RASI/Mykrobe/mccortex/bin/mccortex31 geno -q -t 1 -m 1GB -k 15 -o /tmp//test2-15_staph-species-160227-staph-amr-bradley_2015-feb-17-2017.covgs -I /tools/linuxbrew/lib/python3.6/site-packages/mykatlas/atlas/data/skeletons/staph-species-160227-staph-amr-bradley_2015-feb-17-2017_15.ctx -s test2-15 -1 55-100-060_R1.fastq.gz -1 55-100-060_R2.fastq.gz -c /tools/linuxbrew/lib/python3.6/site-packages/mykrobe/data/panels/staph-species-160227.fasta.gz -c /tools/linuxbrew/lib/python3.6/site-packages/mykrobe/data/panels/staph-amr-bradley_2015-feb-17-2017.fasta.gz /tmp//test2-15_staph-species-160227-staph-amr-bradley_2015-feb-17-2017.ctx
Error: Unrecognised command: geno
usage: mccortex31 <command> [options] <args>
version: mccortex=v0.0.3-554-ga7d6f3b zlib=1.2.11 htslib=1.3.2-208-gd8d0323 ASSERTS=ON hash=Lookup3 CHECKS=ON k=3..31

[usage removed]

Traceback (most recent call last):
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykatlas/cortex/mccortex.py", line 210, in _run_coverage_if_required
    subprocess.check_output(self.coverages_cmd)
  File "/tools/linuxbrew/opt/python3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/tools/linuxbrew/opt/python3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/srv/data/AS/RASI/Mykrobe/mccortex/bin/mccortex31', 'geno', '-q', '-t', '1', '-m 1GB', '-k', '15', '-o', '/tmp//test2-15_staph-species-160227-staph-amr-bradley_2015-feb-17-2017.covgs', '-I', '/tools/linuxbrew/lib/python3.6/site-packages/mykatlas/atlas/data/skeletons/staph-species-160227-staph-amr-bradley_2015-feb-17-2017_15.ctx', '-s', 'test2-15', '-1', '55-100-060_R1.fastq.gz', '-1', '55-100-060_R2.fastq.gz', '-c', '/tools/linuxbrew/lib/python3.6/site-packages/mykrobe/data/panels/staph-species-160227.fasta.gz', '-c', '/tools/linuxbrew/lib/python3.6/site-packages/mykrobe/data/panels/staph-amr-bradley_2015-feb-17-2017.fasta.gz', '/tmp//test2-15_staph-species-160227-staph-amr-bradley_2015-feb-17-2017.ctx']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tools/linuxbrew/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykrobe/mykrobe_predictor.py", line 125, in main
    args.func(parser, args)
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykrobe/mykrobe_predictor.py", line 34, in run_subtool
    run(parser, args)
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykrobe/cmds/amr.py", line 134, in run
    cp.run()
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykatlas/typing/typer/genotyper.py", line 73, in run
    self._run_cortex()
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykatlas/typing/typer/genotyper.py", line 90, in _run_cortex
    self.mc_cortex_runner.run()
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykatlas/cortex/mccortex.py", line 161, in run
    self._run_cortex()
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykatlas/cortex/mccortex.py", line 175, in _run_cortex
    self._run_coverage_if_required()
  File "/tools/linuxbrew/opt/python3/lib/python3.6/site-packages/mykatlas/cortex/mccortex.py", line 213, in _run_coverage_if_required
    "mccortex31 raised an error. Is it on PATH? check by running `mccortex31 geno`. The command that through the error was `%s`  " % subprocess.list2cmdline(self.coverages_cmd))
ValueError: mccortex31 raised an error. Is it on PATH? check by running `mccortex31 geno`. The command that through the error was `/srv/data/AS/RASI/Mykrobe/mccortex/bin/mccortex31 geno -q -t 1 "-m 1GB" -k 15 -o /tmp//test2-15_staph-species-160227-staph-amr-bradley_2015-feb-17-2017.covgs -I /tools/linuxbrew/lib/python3.6/site-packages/mykatlas/atlas/data/skeletons/staph-species-160227-staph-amr-bradley_2015-feb-17-2017_15.ctx -s test2-15 -1 55-100-060_R1.fastq.gz -1 55-100-060_R2.fastq.gz -c /tools/linuxbrew/lib/python3.6/site-packages/mykrobe/data/panels/staph-species-160227.fasta.gz -c /tools/linuxbrew/lib/python3.6/site-packages/mykrobe/data/panels/staph-amr-bradley_2015-feb-17-2017.fasta.gz /tmp//test2-15_staph-species-160227-staph-amr-bradley_2015-feb-17-2017.ctx`

**Comment by idolawoye** [comment]
I have similar issue. Were you able to resolve it? @RaSieb

**Comment by iqbal-lab** [comment]
Hi all. we are now moving from this repo to a new one, with much updated code:
https://github.com/mykrobe-tools/mykrobe
could you try this? We will be publicising the new version/repo in a few weeks.

**Comment by idolawoye** [comment]
Thanks @iqbal-lab the new repo worked perfectly.

**Comment by iqbal-lab** [comment]
Awesome
