### ISSUE TITLE
need a option for the output file

### ISSUE THREAD

**Issue by yujun2017** [iqbal-lab/Mykrobe-predictor#132]
we tried to use this application and want to know if there is a option to setup output file.

**Comment by iqbal-lab** [comment]
Do you mean the windows/mac application or the command line tool ?

**Comment by yujun2017** [comment]
We are using The command line tool

**Comment by Phelimb** [comment]
There's currently no option to modify the output. However, you can use the script json_to_tsv to convert the json results into tabular format.
