### ISSUE TITLE
__init__() got an unexpected keyword argument 'include_hom_alt_calls'

### ISSUE THREAD

**Issue by daarojasos** [iqbal-lab/Mykrobe-predictor#139]
I am getting the error message:   TypeError: __init__() got an unexpected keyword argument 'include_hom_alt_calls'

Any ideas about why this is happening?   
Thanks U all!

**Comment by Phelimb** [comment]
@daarojasos this should be fixed in https://github.com/Mykrobe-tools/mykrobe
