### ISSUE TITLE
Request: save the .json file for later use

### ISSUE THREAD

**Issue by RaSieb** [iqbal-lab/Mykrobe-predictor#141]
With the latest commit, the `.json` formatted output is not separated anymore. This makes it difficult to parse the actual output (without debug messages etc.) for further use, as well as for piping. 

Is there a way the actual `.json` file could be saved to disk, or the return could be separated into `stdout` and `stderr`?

**Comment by iqbal-lab** [comment]
cc @rffrancon @Phelimb

**Comment by idolawoye** [comment]
Hello, 
I have similar request as the OP so I just want to know if there is a way to go about that now as I run my analysis on the commandline and it will be great if we can have the output in a ```.json``` file saved on the hard disk.

**Comment by iqbal-lab** [comment]
Hi there - is there a reason, if running on the command line, you cannot save stdout?
Anyway, we're about to make a big release, will take this feedback

**Comment by iqbal-lab** [comment]
I'll close this as you have a workaround (write stdout to a file). The new release already has a commandline option to allow you to write to a file, so you'll have that too soon
