### ISSUE TITLE
Question about resistance report.   R  vs r

### ISSUE THREAD

**Issue by harrismia** [iqbal-lab/Mykrobe-predictor#144]
Hi, 

        What is the difference between R  vs   r   in the resistance report?   
For example see Quinolones in the report below:   Thanks.

Probe sets :tb-species-170421.fasta.gz,tb-walker-probe-set-feb-09-2017.fasta.gz
 
Drug susceptibility: 

	Rifampicin	R	rpoB_S450L-S450L	rpoB_S450F-S450F	rpoB_S450I-S450I	
	Streptomycin	R	rpsL_K43R-K43R	
	Amikacin	S	
	Ethambutol	R	embB_M306V-M306V	
	Kanamycin	S	
	Pyrazinamide	R	pncA_Q141P-Q141P	
	Isoniazid	R	katG_S315T-S315T	katG_S315N-S315N	
	Capreomycin	S	
	Quinolones	r	
	lineage	Beijing_East_Asia
	species	Mycobacterium_tuberculosis
	sub_complex	Unknown
	phylo_group	Mycobacterium_tuberculosis_complex_

**Comment by iqbal-lab** [comment]
Lower case r means we detect an allele, but at a low/minor within-sample frequency.
For example if we had 100x depth, and we saw 20x on a resistance allele, we would report it as r, as it would be more likely to be a low frequency allele than a sequencing error.

Please reopen if this is unclear

**Comment by harrismia** [comment]
Thanks for the explanation!    When there is a r  there is no variant reported.  Is this expected?
