### ISSUE TITLE
mykrobe --version  on linux shows  mykrobe v0.5.6-0-gbd7923a-dirty .  Is this version OK to use?

### ISSUE THREAD

**Issue by harrismia** [iqbal-lab/Mykrobe-predictor#145]
Hello,  

        We originally had some issues getting mykrobe installed on our linux cluster but it now seems to be working fine.   Typing the command  :      mykrobe  --version   produces:   v0.5.6-0-gbd7923a-dirty

       Is this version OK to use?   The   "-dirty" on the version number caused me to ask the question.  Thanks !   Michael

**Comment by iqbal-lab** [comment]
I have never liked having dirty there, but yes, it is ok. Closing. @Phelimb - feel free to comment where "dirty" comes from.

**Comment by harrismia** [comment]
Thanks!

Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764  |  Mobile 301-509-0233
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by flashton2003** [comment]
@Phelimb where does the dirty come from?
