### ISSUE TITLE
Coll et al lineage/sub-lineage from Mykrobe

### ISSUE THREAD

**Issue by flashton2003** [iqbal-lab/Mykrobe-predictor#150]
I think it would be useful for Mykrobe to output the Coll et al lineage/sub-lineage, e.g. 2.2.1.1 from this manuscript. The SNPs/positions are available in the supplementary materials of the paper.

https://www.nature.com/articles/ncomms5812

**Comment by iqbal-lab** [comment]
Yep this is already on the plan, quite agree

**Comment by Phelimb** [comment]
Moved to https://github.com/Mykrobe-tools/mykrobe/issues/47
