### ISSUE TITLE
No evidence given for inducible Clindamycin resistance

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/Mykrobe-predictor#16]
When we call inducible R for clindamycin because an erm gene is present, we don't say so in the JSON. Eg currently we have things like this

{
                        "expected_depth": "140",
                        "mean_read_length": "89",
                "species": {
                "S.aureus": "Major"
                },
        "susceptibility" :{
                "Gentamicin": "S",
                "Penicillin": "S",
                "Methicillin": "S",
                "Trimethoprim": "S",
                "Erythromycin": "R",
                "FusidicAcid": "S",
                "Ciprofloxacin": "S",
                "Rifampicin": "S",
                "Tetracycline": "S",
                "Vancomycin": "S",
                "Mupirocin": "S",
                "Clindamycin": "R(inducible)"
        },
        "called_variants" :{
        },
        "called_genes" :{
                "ermC" :{
                        "per_cov": "99",
                        "median_cov": "1627",
                "induced_resistance": "Erythromycin"
                }
        },
        "virulence_toxins" :{
                "PVL": "negative"
        }
}

Really we should also say
                "ermC" :{
                        "per_cov": "99",
                        "median_cov": "1627",
                "induced_resistance": "Erythromycin, Clindamycin"
                }

**Comment by Phelimb** [comment]
induced_by format has changed in latests so this should be fixed
