### ISSUE TITLE
Missing checks for malloc failures

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/Mykrobe-predictor#59]
eg this in base_species.c

boolean* create_mask(boolean default_value)
{
  boolean* mask = malloc(NUM_SPECIES * sizeof(boolean));

Should check afterwards
eg

if (mask==NULL)
{
  fail or return error message
}

Ties into bigger picture of improving error handling being passed back to app

**Comment by iqbal-lab** [comment]
Phelim, is this still open?

**Comment by Phelimb** [comment]
I think so. Will take a look on dev and fix before merging to master.
