### ISSUE TITLE
Don't display r if coverage is better explained by a contaminating species than by target species. 

### ISSUE THREAD

**Issue by Phelimb** [iqbal-lab/Mykrobe-predictor#74]
E.g. RH12000540-156-1

We have 

                        "Staphylococcus aureus": "159",
                        "Coagulase-Negative Staphylococcus": "5"

and 

                "blaZ" :{
                        "per_cov": "100",
                        "median_cov": "10",
                        "conf": "31",
                "induced_resistance": "Penicillin"
                },
                "ermA" :{
                        "per_cov": "100",
                        "median_cov": "18",
                        "conf": "62",
                "induced_resistance": "Erythromycin"
                },
                "mecA" :{
                        "per_cov": "95",
                        "median_cov": "3",
                        "conf": "3",
                "indu

These calls are better explained by the genes existing in the contaminate rather than the aureus. It would be nice if we didn't report r in these cases but report S instead.

**Comment by iqbal-lab** [comment]
I think this is fixed on your branch Phelim, so will be fixed by when we pull that in

**Comment by Phelimb** [comment]
Nope. Not fixed on my branch yet.

**Comment by iqbal-lab** [comment]
really? I'm sure you've shown me examples

**Comment by Phelimb** [comment]
I think I showed you an example where it would be good if this is what did
happen but pretty sure it's not implemented.

**Comment by Phelimb** [comment]
Closed by https://github.com/iqbal-lab/Mykrobe-predictor/commit/013a0183b8582c58315704e75a39b952476001cb
