### ISSUE TITLE
Installation  Error: 1

### ISSUE THREAD

**Issue by AC-genomics** [iqbal-lab/Mykrobe-predictor#76]
/usr/bin/ld: cannot find -lseqfile
/usr/bin/ld: cannot find -lstrbuf
/usr/bin/ld: cannot find -lhts
collect2: error: ld returned 1 exit status
make: *** [predictor] Error 1

**Comment by iqbal-lab** [comment]
OK, Can you please give the full command-line instructions and everything that printed on the screen for
1. your install of Mykrobe-predictor
2. you compilation

**Comment by AC-genomics** [comment]
anirvan@ubuntu:~/Downloads/Mykrobe-predictor$ make TB=1 predictor
rm -rf src/obj/*
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/basic/global.c -o src/obj/predictor/global.o
libs/cortex/src/basic/global.c: In function ‘strbuf_remove_all_whitespace’:
libs/cortex/src/basic/global.c:202:5: warning: implicit declaration of function ‘isspace’ [-Wimplicit-function-declaration]
     if(!isspace(str[i]))
     ^
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/tb/main.c -o src/obj/predictor/main.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/tb/antibiotics.c -o src/obj/predictor/antibiotics.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/basic/binary_kmer.c -o src/obj/predictor/binary_kmer.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/element.c -o src/obj/predictor/element.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/basic/seq.c -o src/obj/predictor/seq.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/hash_table/hash_key/bob_jenkins/hash_value.c -o src/obj/predictor/hash_value.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/hash_table/open_hash/hash_table.c -o src/obj/predictor/hash_table.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/build.c -o src/obj/predictor/build.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/dB_graph_supernode.c -o src/obj/predictor/dB_graph_supernode.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/graph_info.c -o src/obj/predictor/graph_info.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/dB_graph.c -o src/obj/predictor/dB_graph.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/db_variants.c -o src/obj/predictor/db_variants.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/tb/cmd_line.c -o src/obj/predictor/cmd_line.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/basic/event_encoding/base_encoding/event_encoding.c -o src/obj/predictor/event_encoding.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/db_differentiation.c -o src/obj/predictor/db_differentiation.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/core/genotyping_known.c -o src/obj/predictor/genotyping_known.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/core/known_mutations.c -o src/obj/predictor/known_mutations.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/core/gene_presence.c -o src/obj/predictor/gene_presence.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/tb/species.c -o src/obj/predictor/species.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/maths.c -o src/obj/predictor/maths.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/core/file_reader.c -o src/obj/predictor/file_reader.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/core/mut_models.c -o src/obj/predictor/mut_models.o
src/predictor/core/mut_models.c: In function ‘get_log_posterior_truly_resistant_plus_errors_on_suscep_allele’:
src/predictor/core/mut_models.c:23:7: warning: unused variable ‘p’ [-Wunused-variable]
   int p = max_perc_covg_on_res_allele;
       ^
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/core/gene_presence_models.c -o src/obj/predictor/gene_presence_models.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/core/json.c -o src/obj/predictor/json.o
mkdir -p src/obj/predictor; gcc -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c src/predictor/core/base_species.c -o src/obj/predictor/base_species.o
mkdir -p bin; gcc -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1  -o bin/"Mykrobe.predictor.tb" src/obj/predictor/global.o src/obj/predictor/main.o src/obj/predictor/antibiotics.o src/obj/predictor/binary_kmer.o src/obj/predictor/element.o src/obj/predictor/seq.o src/obj/predictor/hash_value.o src/obj/predictor/hash_table.o src/obj/predictor/build.o src/obj/predictor/dB_graph_supernode.o src/obj/predictor/graph_info.o  src/obj/predictor/dB_graph.o src/obj/predictor/db_variants.o src/obj/predictor/cmd_line.o src/obj/predictor/event_encoding.o src/obj/predictor/db_differentiation.o src/obj/predictor/genotyping_known.o src/obj/predictor/known_mutations.o src/obj/predictor/gene_presence.o src/obj/predictor/species.o src/obj/predictor/maths.o src/obj/predictor/file_reader.o src/obj/predictor/mut_models.o src/obj/predictor/gene_presence_models.o  src/obj/predictor/json.o src/obj/predictor/base_species.o -lseqfile -lstrbuf -lhts -lpthread -lz -lm
/usr/bin/ld: cannot find -lseqfile
/usr/bin/ld: cannot find -lstrbuf
/usr/bin/ld: cannot find -lhts
collect2: error: ld returned 1 exit status
make: *** [predictor] Error 1

**Comment by iqbal-lab** [comment]
thanks, but I'd like also the command you used to download Mykrobe-predictor from github. At least, I assume you are Anirvan Chatterjee, who emailed me with a very similar problem, who said they had used --recursive, which surprised me. I'd be grateful if you could show me that output too.

**Comment by iqbal-lab** [comment]
Actually - did you follow the README instructions and type

bash install.sh
or
sh install.sh  

?

**Comment by AC-genomics** [comment]
I missed the shell file. installed now. Thanks.

**Comment by iqbal-lab** [comment]
OK, closing .
