### ISSUE TITLE
output documentation & parser

### ISSUE THREAD

**Issue by stephenturner** [iqbal-lab/Mykrobe-predictor#86]
Need better docs on output and JSON parser. 

- What do the lines in the output refer to:
    - `R_per_cov`
    - `S_per_cov`
    - `R_median_cov`
    - `S_median_cov`
    - `conf`
- Why is `induced_resistant` given under inferred variants, but the resistance profile shows `inconclusive`?

**Comment by iqbal-lab** [comment]
induced resistance means - this is the drug this allele causes resistance in

**Comment by iqbal-lab** [comment]
we could change it to "associated_drug" I suppose

**Comment by Phelimb** [comment]
Agree we should have some more detailed documentation somewhere though. Thoughts on where @iqbal-lab?

Maybe https://mykrobe-predictor.readme.io/docs ? 

I've heard good things.

**Comment by Phelimb** [comment]
Possibly overkill though.

**Comment by stephenturner** [comment]
a few sections in your README.md would be good enough


Stephen

**Comment by stephenturner** [comment]
Thanks! :+1:

**Comment by stephenturner** [comment]
coming back to this, do you have any suggestions for parsing the JSON files? what about for JSON files for multiple runs? any parser to aggregate into some tabular format?

**Comment by iqbal-lab** [comment]
@Phelimb has some stuff - is it public yet Phelim?
