### ISSUE TITLE
allow amplicon data

### ISSUE THREAD

**Issue by stephenturner** [iqbal-lab/Mykrobe-predictor#87]
When using amplicon data the GUI errors out because the probes used to detect M. tb may not be present. The Linux version can be hacked to work by changing `src/predictor/tb/main.c` from `if (!is_MTBC_present(species_info))` to `if(0)` and compile with `make TB=1 predictor`. This would be better as an option to disable checking, and even better if the option were implemented in the GUI.

**Comment by iqbal-lab** [comment]
Phelim will have a think about whether/how we want to support this Stephen.

**Comment by Phelimb** [comment]
Possible way is a -f --force option which forces resistance prediction even when species is not TB?

**Comment by Phelimb** [comment]
GUI will be trickier - perhaps default if not TB should be to go to the species page with a warning that resistance predictions could be incorrect because we don't think the species is TB but allow the user to proceed at their own risk ?

**Comment by iqbal-lab** [comment]
Or don't support GUI for amplicons.

**Comment by stephenturner** [comment]
How about a "proceed at your own risk" warning :)


Stephen
