### ISSUE TITLE
ImportError: cannot import name unique

### ISSUE THREAD

**Issue by tseemann** [iqbal-lab/Mykrobe-predictor#91]
Trying to run the setup fails. I tried `pip install utils` but still no luck:
```
% code_generator $ python staph.py
Traceback (most recent call last):
  File "staph.py", line 2, in <module>
    from utils import unique,flatten
ImportError: cannot import name unique
```

**Comment by iqbal-lab** [comment]
Torsten - Phelim is away for a few days, will get back to you asap on this.

**Comment by Phelimb** [comment]
@tseemann if you want to play with the code_generator then I'd recommend you checkout the dev branch (where this is also fixed). We're doing some final testing before merging it into master. 

I'll also push a quick fix for this into master.

**Comment by iqbal-lab** [comment]
Torsten says this is not fixed. Phelim, feel free to say you won't fix this til you merge dev/

**Comment by iqbal-lab** [comment]
Ping.

**Comment by iqbal-lab** [comment]
Ping - is this still open now that PR is merged?
