### ISSUE TITLE
make: *** No rule to make target `src/obj/predictor/main.o', needed by `predictor'.  Stop.

### ISSUE THREAD

**Issue by FelipeMelis** [iqbal-lab/Mykrobe-predictor#94]
I've run  `make TB=1 predictor` and get this (i have the same problem with the code generator for fbarius) 
(I've no problem with `make STAPH=1 predictor`)

```
    rm -rf src/obj/*
mkdir -p src/obj/predictor; gcc-4.9 -Ilibs/cortex/include/core -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table  -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -L -Iinclude/predictor/core -Ilibs/cortex/include/basic -Ilibs/cortex/include/hash_table -Iinclude/predictor/tb -Ilibs/cortex/include/basic/event_encoding/base_encoding -L/usr/local/lib  -Ilibs/htslib/htslib -Ilibs/seq_file -Ilibs/string_buffer -Llibs/htslib/htslib -Llibs/seq_file -Llibs/string_buffer -L -O3 -m64 -Wall  -DWINDOWS=0 -DVERSION_STR='""' -DNUMBER_OF_BITFIELDS_IN_BINARY_KMER=1 -DNUMBER_OF_COLOURS=1 -DTB=1 -c libs/cortex/src/basic/global.c -o src/obj/predictor/global.o
libs/cortex/src/basic/global.c: In function 'strbuf_remove_all_whitespace':
libs/cortex/src/basic/global.c:202:5: warning: implicit declaration of function 'isspace' [-Wimplicit-function-declaration]
     if(!isspace(str[i]))
     ^
make: *** No rule to make target `src/obj/predictor/main.o', needed by `predictor'.  Stop.   
```

**Comment by Phelimb** [comment]
Hi Felipe, 

Thanks for the issue. I've just pushed a fix - I mistakenly pushed a change that commented out necessary lines. If you pull 971bfe42f290d71cce9468f81ee5dc76f0ad6983 and rerun ./make.sh you should make the TB app successfully.

**Comment by FelipeMelis** [comment]
Hi,

i still have the same problem

**Comment by Phelimb** [comment]
Could you try running the following commands and see if you get any warnings or errors? 

cd code_generator
python tb.py
cd ..

set +e
cd data/skeleton_binary/tb/
ls ../../tb/antibiotics/*.fa > list_speciesbranches_genes_and_muts
ls ../../tb/virulence/*.fa >> list_speciesbranches_genes_and_muts
ls ../../tb/phylo/*/*.fa >> list_speciesbranches_genes_and_muts
cd ../../../
set -e

cp code_generator/rendered/include/predictor/core/* include/predictor/core/
cp code_generator/rendered/include/predictor/tb/* include/predictor/tb/
cp code_generator/rendered/src/predictor/core/* src/predictor/core/
cp code_generator/rendered/src/predictor/tb/* src/predictor/tb/

make TB=1 predictor
cd bin
./mykrobe.predictor.tb  --file ../data/tb/phylo/phylo_group/MTBC.fa --install_dir ../ > /tmp/MTBC.json
cd ..

**Comment by FelipeMelis** [comment]
Thanks!!

Finally Works!

**Comment by Phelimb** [comment]
:+1:

**Comment by FelipeMelis** [comment]
But .. i get this error when i execute `./mykrobe.predictor.tb --file ../data/tb/phylo/phylo_group/MTBC.fa --install_dir ../ > /tmp/MTBC.json``
`
seq_file.c:255: Warning -- plain file starts with non-ACGTN base
seq_file.c:264: Error -- ungetc failed
`
i try with fastq files and i get the same error
