### ISSUE TITLE
Problem with code_generator

### ISSUE THREAD

**Issue by FelipeMelis** [iqbal-lab/Mykrobe-predictor#95]
The next lines are from `foo_bar.py`
````
    @property 
    def drugs(self):
        return [StaphDrugCodeGenerator(drug) for drug in self.drug_names ]

```
should say FooBarDrugCodeGenerator instead StaphDrugCodeGenerator?

```
cd code_generator
python fbarius.py
cd ..
```
should say foo_bar.py instead fbarius.py?

**Comment by Phelimb** [comment]
Hi Felipe, 

You're right StaphDrugCodeGenerator should be FooBarDrugCodeGenerator  and foo_bar.py should read fbarius.py (or vice versa). 

If you have a specific species or panel you'd like to try out I'd be happy to help you out. The code generator has only been used by me so far so there's likely to be some bugs to iron out.

**Comment by FelipeMelis** [comment]
Yes i want to extend mykrobe to others genomes, i follow the tutorial but i`ve some problems with it

**Comment by Phelimb** [comment]
OK, any specific spot where the problems are arising? 

Do you want to look at gene presence alone or do you want to consider variants also (or both).

**Comment by FelipeMelis** [comment]
I will try again with the code_generator and i ask you again.

I want to look first the gene presence.

**Comment by Phelimb** [comment]
OK, 

You'll need a fasta file for each gene in data/:new_species/antibiotics

and a json or dictionary in code_generator/:new_species/gene_to_drug.json. 

You look at the current code that exists where :new_species -> staph you should be able to modify it for your purpose. 

Happy to help with this so keep me posted.

**Comment by FelipeMelis** [comment]
Hello,

I trying to modify the makefile, and i have problems with that
I only have to adds this lines?

```
Modify the Makefile to include:

IDIR_PREDICTOR_FBARIUS = include/predictor/fbarius
src/obj/predictor/%.o : src/predictor/fbarius/%.c include/predictor/fbarius/%.h
    mkdir -p src/obj/predictor; $(CC) $(CFLAGS_PREDICTOR_CORE) $(CFLAGS_PREDICTOR) $(OPT) -c $< -o $@   
```

**Comment by Phelimb** [comment]
Hi @FelipeMelis. We've changed the method for extending Mykrobe as the code generator wasn't working very well. 

Please install the new version and try out the "Genotype on a catalog" section of the readme. You just need to provide a fasta of your gene panel to type. I'll write up some details on how to extend a gene panel and species ID shortly. 

Let me know if you get a chance to try this out.
