### ISSUE TITLE
seq_file.c:255: Warning -- plain file starts with non-ACGTN

### ISSUE THREAD

**Issue by FelipeMelis** [iqbal-lab/Mykrobe-predictor#96]
I get this error when i execute `mykrobe.predictor.tb` or `mykrobe.predictor.staph`, i am using fastq files.

```
seq_file.c:255: Warning -- plain file starts with non-ACGTN base
seq_file.c:264: Error -- ungetc failed
```

**Comment by Phelimb** [comment]
Can you copy the full command you've used? Did you use --list or --file? 

If possible could you also show the output of 

head fasta.fq

?

**Comment by FelipeMelis** [comment]
The command i use:

```$ ./mykrobe.predictor.staph --file demo_input_file_for_S.aureus_app.fastq --install_dir ../ ```

The head of the fastq file is:

```
@GAII04_0003:1:1:1006:19391#GCCAAT
NTGTAAGCTTTGTTTGTTAATTGCTCTTGTAGTTCATAGTTAATATACACA
+
#//+.99;99A@=>42>;>?<==>=@?@@<67;;;:::::<<;<=@??A@#
@GAII04_0003:1:1:1008:19779#GCCAAT
NAGAAGAGAAGAAGTAGATGCATTTTTAGATGACATTATTGCTGATTATCA
+
#**('+%+(+:978<>=<<=@@?@?22'89<<>>8A??A=7::=:::<:6<
@GAII04_0003:1:1:1011:1443#GCCAAT
NTCGCTATTCTGACGATAATTTTAACGATAATTGCTTTGATTTTTTTGCCA
```

**Comment by Phelimb** [comment]
I can't seem to replicate. What operating system are you using ?

**Comment by FelipeMelis** [comment]
I am using MacOSX the yosemite version.

**Comment by iqbal-lab** [comment]
seq_ungetc depends on existence of gzungetc. Is is possible zlib is not installed or something?

**Comment by Phelimb** [comment]
xcode-select --install 

should install zlib on a mac if it's not already. Could you try that @FelipeMelis  and see if it helps?

**Comment by FelipeMelis** [comment]
I have already install xcode on my mac (even update the xcode and doesn`t work).

**Comment by FelipeMelis** [comment]
Finally i used a linux environment and works fine.
Thanks for all your helps.
