### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by milieuziektes** [iqbal-lab/Mykrobe-predictor#97]
I downloaded the two exe files from the main page, where no typical Windows versions were mentioned.
I tried on WindowsXP SP3 (32bit) where I got the message: _Access denied_
However, it runs fine on Windows7 64bit.

**Comment by iqbal-lab** [comment]
We need to update Mykrobe.com to specify which OS it supports

**Comment by iqbal-lab** [comment]
ie bug in documentaton

**Comment by Phelimb** [comment]
@iqbal-lab Where do you want to document this? On mykrobe.com?

**Comment by iqbal-lab** [comment]
I think mykrobe.com should prob be fixed to say 64bit. Or can point to github. Github - enought o say in readme no?
