### ISSUE TITLE
Possible floating point error when calculating DFR* thresholds

### ISSUE THREAD

**Issue by Phelimb** [iqbal-lab/Mykrobe-predictor#98]
Should return r if > 0.03 but returns S if < 0.035.

**Comment by Phelimb** [comment]
Actually problem here was a small bug causing trim to use 0.04 as threshold (BlaZ's) instead of 0.03.

**Comment by iqbal-lab** [comment]
How did you spot this btw ?

**Comment by Phelimb** [comment]
I got an email from a user who spotted two inconsistent samples.

**Comment by iqbal-lab** [comment]
Great!
