### ISSUE TITLE
We should document how to parallelise

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/Mykrobe-predictor#99]
Just give a simple GNU parallels command people can copy.

**Comment by RaSieb** [comment]
Hi
I've uploaded some scripts to use Mykrobe predictor staph and the "mykrobe genotype" on sets of illumina paired end reads to my GitHub: https://github.com/RaSieb/batchMykrobe. 
Required is an input directory containing sequence read files with _R1.fastq.gz and _R2.fastq.gz endings and for the genotype option a panel. 
The output is the .json files in the output directory, which can be coerced into a .tsv table with one line per sample with the additional python scripts.  
Hopefully someone will find them useful. 
The scripts are written for mac.
